apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f iris-compose.yaml
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: iris
  name: iris
spec:
  ports:
  - name: "9092"
    port: 9092
    targetPort: 52773
  - name: "9091"
    port: 9091
    targetPort: 51773
  selector:
    io.kompose.service: iris
status:
  loadBalancer: {}
